# Generated by Django 4.2.7 on 2023-11-29 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poryect',
            old_name='chearted_at',
            new_name='created_at',
        ),
    ]
